/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-nlembedding.h
 #	source generated by 4D Plugin Wizard
 #	Project : nlembedding
 #	author : eric marchand
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_NLEMBEDDING_H
#define PLUGIN_NLEMBEDDING_H

#include "4DPluginAPI.h"
#include <string>
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"
#include <chrono>
#import <AppKit/AppKit.h>
#import <NaturalLanguage/NaturalLanguage.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>

#pragma mark -

void word_embedding(PA_PluginParameters params);
void sentence_embedding(PA_PluginParameters params);

#endif /* PLUGIN_NLEMBEDDING_H */
